/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DiskCache {
  constructor(path?: string | undefined | null)
  static defaultPath(): string
  get(domain: string, ttl: number): CachedRowJs | null
  put(domain: string, zone: string, status: string, detail: string): void
}
export type JsDiskCache = DiskCache

export interface CachedRowJs {
  domain: string
  zone: string
  status: string
  detail: string
  checkedAt: number
}

export declare function checkMany(domains: Array<string>, concurrency?: number | undefined | null, timeout?: number | undefined | null, cache?: JsDiskCache | undefined | null, cacheTtl?: number | undefined | null, verify?: boolean | undefined | null): Array<CheckRow>

export interface CheckRow {
  input: string
  domain: string
  zone: string
  status: string
  detail: string
  fromCache: boolean
}

export declare function loadRules(path: string): void
